remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Katteetaten
description: De som får tilbud om hjelp gjennom kattehjelpen, får personlig oppfølging og kontakt. Målet er å finne løsninger innenfor regelverket som kan forbedre situasjonen og gjøre kattebetaleren i stand til å betale riktig katt. Hver enkelt sak blir vurdert individuelt.
